# Generated by Django 6.0.7 on 2026-07-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.PositiveIntegerField(default=1000, verbose_name='Цена от'),
            preserve_default=False,
        ),
    ]
