# Generated by Django 6.0.7 on 2026-07-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_main', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название тура')),
                ('hotel', models.CharField(max_length=150, verbose_name='Отель')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Фото')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=2, verbose_name='Рейтинг')),
                ('nights', models.PositiveIntegerField(default=7, verbose_name='Ночей')),
                ('departure', models.CharField(default='Москва', max_length=100, verbose_name='Вылет')),
                ('food', models.CharField(default='Всё включено', max_length=100, verbose_name='Питание')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Горящий тур')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Скидка (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='tours_main.destination', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
                'ordering': ['price'],
            },
        ),
    ]
