# Generated by Django 6.0.7 on 2026-07-20 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_main', '0003_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_gallery/', verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours_main.tour', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Фотография тура',
                'verbose_name_plural': 'Фотографии тура',
                'ordering': ['order'],
            },
        ),
    ]
