# Generated by Django 6.0.7 on 2026-08-19 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_main', '0004_tourimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='Номер брони')),
                ('hotel_name', models.CharField(blank=True, max_length=160, verbose_name='Отель')),
                ('date_from', models.DateField(verbose_name='Заезд')),
                ('date_to', models.DateField(verbose_name='Выезд')),
                ('depart_at', models.DateTimeField(blank=True, help_text='Нужно для обратного отсчёта на главном экране кабинета', null=True, verbose_name='Вылет')),
                ('adults', models.PositiveSmallIntegerField(default=2, verbose_name='Взрослых')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='Детей')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Стоимость, ₽')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящая'), ('done', 'Завершённая'), ('canceled', 'Отменённая')], default='upcoming', max_length=12, verbose_name='Статус')),
                ('payment', models.CharField(choices=[('paid', 'Оплачено полностью'), ('partial', 'Внесена предоплата'), ('await', 'Ждём оплату'), ('refund', 'Возврат произведён')], default='partial', max_length=12, verbose_name='Оплата')),
                ('readiness', models.PositiveSmallIntegerField(default=40, verbose_name='Готовность к поездке, %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours_main.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-date_from'],
            },
        ),
        migrations.CreateModel(
            name='MilesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Операция')),
                ('amount', models.IntegerField(verbose_name='Мили (+ начисление / − списание)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miles_log', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Операция с милями',
                'verbose_name_plural': 'История миль',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('tone', models.CharField(choices=[('blue', 'Информация'), ('mint', 'Успех'), ('amber', 'Требует внимания')], default='blue', max_length=8, verbose_name='Тип')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('home_city', models.CharField(blank=True, default='Москва', max_length=64, verbose_name='Город вылета')),
                ('preferences', models.TextField(blank=True, verbose_name='Пожелания к поездкам')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='basic', max_length=12, verbose_name='Уровень')),
                ('miles', models.PositiveIntegerField(default=0, verbose_name='Бонусные мили')),
                ('notify_email', models.BooleanField(default=True, verbose_name='Уведомления на email')),
                ('notify_sms', models.BooleanField(default=True, verbose_name='Уведомления по SMS')),
                ('notify_telegram', models.BooleanField(default=False, verbose_name='Уведомления в Telegram')),
                ('notify_price', models.BooleanField(default=True, verbose_name='Сообщать о снижении цены')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль клиента',
                'verbose_name_plural': 'Клиенты (профили)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Название')),
                ('meta', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('ok', 'Проверен'), ('need', 'Нужен файл'), ('progress', 'На оформлении')], default='need', max_length=12, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Документ туриста',
                'verbose_name_plural': 'Документы туристов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tours_main.tour', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Избранный тур',
                'verbose_name_plural': 'Избранные туры',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'tour')},
            },
        ),
    ]
