# Generated by Django 6.0.7 on 2026-08-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_main', '0005_booking_milesentry_notification_profile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Направление', 'verbose_name_plural': 'Направления'},
        ),
        migrations.AddField(
            model_name='booking',
            name='miles_awarded',
            field=models.BooleanField(default=False, help_text='Ставится автоматически, когда поездка становится завершённой', verbose_name='Мили за поездку начислены'),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured',
            field=models.BooleanField(default=True, help_text='Снимите галочку, если направление не должно попадать в блок «Рекомендуемые направления»', verbose_name='Рекомендовать в личном кабинете'),
        ),
        migrations.AddField(
            model_name='destination',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок вывода'),
        ),
    ]
